{% set name = "nbodykit" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 6
  script : $PYTHON setup.py install --single-version-externally-managed  --record rec.txt

requirements:
  host:
    - python
    - numpy

  run:
    - python
    - numpy
    - scipy
    - astropy
    - mpi4py
    - runtests
    - pmesh
    - kdcount
    - mpsort
    - bigfile
    - pandas
    - dask >=0.13
    - cachey
    - h5py
    - halotools
    - fitsio
    - classylss >=0.2
    - mcfit
    - sympy !=1.6.0, !=1.6.1
    - numexpr
    - corrfunc

test:
  # Python imports
  imports:
    - nbodykit

about:
  home: http://github.com/bccp/nbodykit
  license: GPL3
  summary: 'Analysis kit for large-scale structure datasets, the massively parallel way'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
