{% set build = 0 %}
{% set version = '0.0.14' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: {{ crayhost }}.prgenv.gnu_linux-64
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]

test:
    files:
      - tests/helloworld.c
      - tests/helloworld.cxx
      - tests/helloworld.f
      - tests/helloworld.f90

run_exports:
  strong:
     - {{ crayhost }}.prgenv.gnu_linux-64

extra:
    recipe-maintainers:
        - rainwoodman
