# Build specific versions by specifying 'version'
# If 'version' not specified, latest release from pypi is built
# To build past versions in addition, specify a 'past_versions' list

- name: mpi4py_test

- name: runtests

- name: kdcount

- name: pfft-python

- name: classylss

- name: bigfile

- name: mpsort

- name: pmesh

- name: nbodykit
  past_versions: [0.1.11]

- name: abopt

- name: vmad

- name: cachey

- name: healpy

- name: fastpm

- name: fitsio

- name: halotools

# needs manual update of common.mk.in against
# the source code !
- name: Corrfunc
  version : 2.2.0

- name: mcfit

- name: fake_spectra

- name: wurlitzer
