{% set name = "Corrfunc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/manodeep/Corrfunc/archive/{{ version }}.tar.gz
#  git_url: https://github.com/nickhand/Corrfunc.git
#  git_tag: master

build:
  number : 10

requirements:
  build:
    - '{{ compiler("c") }}'
    - gsl

  host:
    - python
    - numpy
    - future
    - gsl

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - gsl
    - future
    - wurlitzer

# We can probably pin this to pin compatible in the future.
# see https://abi-laboratory.pro/?view=timeline&l=gsl
pin_run_as_build:
    - gsl

test:
  # Python imports
  imports:
    - Corrfunc
    - Corrfunc.tests

about:
  #home: The package home page
  license: MIT
  summary: 'Blazing fast correlation functions on the CPU'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
