{% set build = 6 %}
{% set version = '0.0.1_git54fdc78' %}
{% set major = version.rpartition('.')[0] %}

package:
    name: cfastpm
    version: {{ version }}

source:
  git_url: https://github.com/rainwoodman/fastpm.git
  git_rev: 54fdc78

build:
    number: {{ build }}
    skip: True  # [win]

requirements:
    build:
        - {{ compiler("c") }} # [not win]
        - {{ mpi }} # [not win]
        - gsl

    host :
        - {{ compiler("c") }} # [not win]
        - {{ mpi }} # [not win]
        - gsl

    run :
        - {{ mpi}}
        - gsl

about:
    home: https://github.com/rainwoodman/fastpm
    license: GPL3
    license_family: GPL
    license_file: LICENSE
    summary: 'FastPM'
    description: |
         quasi-nbody simulation with particle mesh

extra:
    recipe-maintainers:
        - rainwoodman
