{% set name = "kdcount" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 5

requirements:
  build:
    - '{{ compiler("c") }}'

  host:
    - python
    - numpy
    - cython

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'

test:
  # Python imports
  imports:
    - kdcount
    - kdcount.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/rainwoodman/kdcount
  license: GPL3
  summary: 'A slower KDTree cross correlator'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
