{% set build = 0 %}
{% set version = '0.0.1' %}
{% set major = version.rpartition('.')[0] %}
package:
    name: {{ crayhost }}.prgenv.gnu.mpi
    version: {{ version }}

build:
    number: {{ build }}
    skip: True  # [win]
    skip: True  # [osx]
    track_features:
     - {{ crayhost }}.prgenv.gnu.mpi

requirements:
    run :
     - {{ crayhost }}.prgenv.gnu_linux-64

extra:
    recipe-maintainers:
        - rainwoodman
