{% set name = "halotools" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 5

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python
    - numpy
    - setuptools
    - astropy >=1
    - scipy
    - beautifulsoup4
    - requests

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - astropy >=1
    - scipy
    - beautifulsoup4
    - requests

test:
  requires:
    - pytest-astropy
  # Python imports
  imports:
    - halotools
    - halotools.empirical_models
    - halotools.empirical_models.abunmatch
    - halotools.empirical_models.abunmatch.tests
    - halotools.empirical_models.assembias_models
    - halotools.empirical_models.assembias_models.tests
    - halotools.empirical_models.component_model_templates
    - halotools.empirical_models.component_model_templates.tests
    - halotools.empirical_models.composite_models
    - halotools.empirical_models.composite_models.hod_models
    - halotools.empirical_models.composite_models.hod_models.tests
    - halotools.empirical_models.composite_models.sfr_models
    - halotools.empirical_models.composite_models.smhm_models
    - halotools.empirical_models.composite_models.tests
    - halotools.empirical_models.factories
    - halotools.empirical_models.factories.tests
    - halotools.empirical_models.occupation_models
    - halotools.empirical_models.occupation_models.engines
    - halotools.empirical_models.occupation_models.tests
    - halotools.empirical_models.phase_space_models
    - halotools.empirical_models.phase_space_models.analytic_models
    - halotools.empirical_models.phase_space_models.analytic_models.centrals
    - halotools.empirical_models.phase_space_models.analytic_models.centrals.tests
    - halotools.empirical_models.phase_space_models.analytic_models.satellites
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.conc_mass
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.conc_mass.tests
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.kernels
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.kernels.tests
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.tests
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.tests.test_biased_nfw
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.tests.test_conc_mass_inheritance
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.tests.test_nfw_phase_space
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.tests.test_nfw_profile
    - halotools.empirical_models.phase_space_models.analytic_models.tests
    - halotools.empirical_models.phase_space_models.subhalo_based_models
    - halotools.empirical_models.phase_space_models.subhalo_based_models.tests
    - halotools.empirical_models.sfr_models
    - halotools.empirical_models.sfr_models.tests
    - halotools.empirical_models.smhm_models
    - halotools.empirical_models.smhm_models.tests
    - halotools.empirical_models.tests
    - halotools.extern
    - halotools.mock_observables
    - halotools.mock_observables.counts_in_cells
    - halotools.mock_observables.counts_in_cells.engines
    - halotools.mock_observables.counts_in_cells.tests
    - halotools.mock_observables.group_identification
    - halotools.mock_observables.group_identification.test_groups
    - halotools.mock_observables.isolation_functions
    - halotools.mock_observables.isolation_functions.engines
    - halotools.mock_observables.isolation_functions.tests
    - halotools.mock_observables.large_scale_density
    - halotools.mock_observables.large_scale_density.tests
    - halotools.mock_observables.pair_counters
    - halotools.mock_observables.pair_counters.cpairs
    - halotools.mock_observables.pair_counters.marked_cpairs
    - halotools.mock_observables.pair_counters.test_pair_counters
    - halotools.mock_observables.pairwise_velocities
    - halotools.mock_observables.pairwise_velocities.engines
    - halotools.mock_observables.pairwise_velocities.tests
    - halotools.mock_observables.radial_profiles
    - halotools.mock_observables.radial_profiles.engines
    - halotools.mock_observables.radial_profiles.tests
    - halotools.mock_observables.surface_density
    - halotools.mock_observables.surface_density.engines
    - halotools.mock_observables.surface_density.tests
    - halotools.mock_observables.tests
    - halotools.mock_observables.two_point_clustering
    - halotools.mock_observables.two_point_clustering.tests
    - halotools.mock_observables.void_statistics
    - halotools.mock_observables.void_statistics.tests
    - halotools.sim_manager
    - halotools.sim_manager.tests
    - halotools.tests
    - halotools.tests.docs_code_block_tests
    - halotools.utils
    - halotools.utils.tests

about:
  home: http://astropy.org/
  license: BSD
  summary: 'Package designed to analyze N-body simulations and constrain models of cosmology and galaxy evolution.'
  license_family: BSD
