{% set name = "classylss" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 6

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("fortran") }}'
    - wget

  host:
    - python
    - numpy
    - setuptools
    - six # only needed to download class, if needed
    - cython

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - cython

test:
  # Python imports
  imports:
    - classylss
    - classylss.binding

about:
  home: http://github.com/nickhand/classylss
  license: GPL3
  summary: 'python binding of CLASS for large-scale structure calculations'
  license_family: GPL3

extra:
  recipe-maintainers:
    - rainwoodman
