{% set name = "vmad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 0
  script : $PYTHON setup.py install --single-version-exteranlly-managed --record rec.txt

requirements:
  host:
    - python
    - numpy

  run:
    - python
    - scipy
    - numpy

test:
  # Python imports
  imports:
    - vmad
    - vmad.tests

about:
  #home: The package home page
  license: GPLv3
  summary: 'Optimization of abstract data types in Python'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
