{% set name = "pmesh" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 2

requirements:
  build:
    - '{{ compiler("c") }}' # [linux]
  host:
    - python
    - numpy
    - cython
    - mpi4py
    - mpsort
    - pfft-python

  run:
    - python
    - '{{ pin_compatible("numpy") }}'
    - cython
    - mpi4py
    - mpsort
    - pfft-python

test:
  # Python imports
  imports:
    - pmesh
    - pmesh.tests

about:
  #home: The package home page
  license: GPL3
  summary: 'Particle Mesh in Python'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
