package:
  name: python-mpi-bcast
  version: 0.1.4

source:
  fn: python-mpi-bcast-0.1.4.tar.gz # [unix]
  url: https://github.com/rainwoodman/python-mpi-bcast/archive/0.1.4.tar.gz

build:
  number: 2
  detect_binary_files_with_prefix: true
  features:
     - '{{ mpi }}'
  skip : True # [osx]
  skip : True # [win]

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ mpi }}'
    - bzip2
    - zlib

  run:
    - '{{ mpi }}'

about:
  home: https://github.com/rainwoodman/python-mpi-bcast
  license: BSD
  summary: Launching Python Applications with MPI Broadcast
  description: |
        Tools for fast launching of python application on clusters with MPI.
        A new Python distribution is deployed to computing nodes at job launch.
