package:
  name: pytorch-cpu
  version: 1.1.0

source:
  # use git checkout to recursively get the submodule dependencies
  # the release tarballs do not carry dependencies.
  git_rev: ec8b1c9
  git_url: https://github.com/pytorch/pytorch/

build:
  detect_binary_files_with_prefix : True
  number: 2
  skip: True  # [win]
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgcc-ng
    - {{ mpi }}
    - numpy
    - pyyaml
    - mkl
    - mkl-include
    - cmake
    - cffi
    - typing
    - python
    - libopenblas

  host:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - libgcc-ng
    - numpy
    - pyyaml
    - mkl
    - cffi
    - typing
    - libopenblas

  run:
    - python
    - numpy
    - libgcc-ng
    - libstdcxx-ng
    - pyyaml
    - mkl
    - cffi
    - typing
    - libopenblas
    - {{ mpi }}

about:
  home: http://www.pytorch.org/
  license: BSD-3
  license_family: BSD
  summary: 'pytorch without GPU, but with MPI'
  description: |
    You know what pytorch is. This build doesn't have GPU support but it has MPI support.

extra:
    recipe-maintainers:
        - rainwoodman

