{% set name = "pfft-python" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 5
  features:
    - '{{ mpi }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ mpi }}'
    - mpi4py
    - numpy
    - cython
    - mpi4py

  host:
    - python
    - numpy
    - cython
    - mpi4py
    - '{{ mpi }}'
    - '{{ compiler("c") }}'

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - mpi4py
    - '{{ mpi }}'

test:
  imports:
    - pfft
    - pfft.tests

about:
  home: http://github.com/rainwoodman/pfft-python
  license: GPL3
  summary: 'python binding of PFFT, a massively parallel FFT library'
  license_family: GPL3

extra:
  recipe-maintainers:
    - rainwoodman
