{% set name = "mpi4py_test" %}

package:
  name: {{ name|lower }}
  version: "{{version}}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number : 1
  script : python setup.py install

requirements:
  host:
    - python
    - numpy
    - mpi4py

  run:
    - python
    - numpy
    - mpi4py

test:
  # Python imports
  imports:
    - mpi4py_test
    - mpi4py_test.tests

about:
  home: http://github.com/rainwoodman/mpi4py_test
  license: BSD-2-Clause
  summary: 'Simple testing based on numpy for applications written with mpi4py.'
  license_family: BSD

extra:
  recipe-maintainers:
    - rainwoodman
