{% set name = "mpsort" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5}}

build:
  number : 5
  features:
    - '{{ mpi }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ mpi }}'
    - mpi4py
    - cython
    - numpy

  host:
    - python
    - numpy
    - cython
    - mpi4py
    - '{{ mpi }}'
    - '{{ compiler("c") }}'

  run:
    - python
    - '{{ pin_compatible("numpy", lower_bound="1.9") }}'
    - mpi4py
    - '{{ mpi }}'

test:
  # Python imports
  imports:
    - mpsort
    - mpsort.tests

about:
  home: http://github.com/rainwoodman/mpsort
  license: BSD-2-Clause
  summary: 'python binding of MP-sort, a peta scale sorting routine'
  license_family: BSD

extra:
  recipe-maintainers:
    - rainwoodman
