# This version of mpi4py disables the build section to avoid
# mpi4py.get_config() pointing to a wrong path.
# This has been fixed (likely due to conda-build) in the default channel.

package:
  name: mpi4py
  version: 3.0.3

source:
  fn: mpi4py-3.0.3.tar.gz # [unix]
  url: https://files.pythonhosted.org/packages/ec/8f/bbd8de5ba566dd77e408d8136e2bab7fdf2b97ce06cab830ba8b50a2f588/mpi4py-3.0.3.tar.gz # [unix]
  sha256: 012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f #[unix]

build:
  number: 999
  detect_binary_files_with_prefix: true

requirements:
# disable build section to make sure mpi4py's get_config() is properly
# set.
#  build:
#    - '{{ compiler("c") }}'

  host:
    - cython
    - python
    - '{{ compiler("c") }}'
    - '{{ mpi }}'

  run:
    - python
    - '{{ mpi }}'

test:
  imports:
    - mpi4py
    - mpi4py.MPI

about:
  home: http://mpi4py.scipy.org/
  license: BSD
  summary: Provides bindings of the MPI standard for Python
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
