package:
  name: mpi4py
  version: 3.0.2

source:
  fn: mpi4py-3.0.2.tar.gz # [unix]
  url: https://files.pythonhosted.org/packages/04/f5/a615603ce4ab7f40b65dba63759455e3da610d9a155d4d4cece1d8fd6706/mpi4py-3.0.2.tar.gz #[unix]
  sha256: f8d629d1e3e3b7b89cb99d0e3bc5505e76cc42089829807950d5c56606ed48e0 #[unix]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - '{{ compiler("c") }}'

  host:
    - python
    - '{{ compiler("c") }}'
    - '{{ mpi }}'

  run:
    - python
    - '{{ mpi }}'

test:
  imports:
    - mpi4py
    - mpi4py.MPI

about:
  home: http://mpi4py.scipy.org/
  license: BSD
  summary: Provides bindings of the MPI standard for Python
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
